<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Blacklist;
use AppBundle\Entity\Whitelist;
use Doctrine\ORM\EntityRepository;

/**
 * JournalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JournalRepository extends EntityRepository {

    public function getJournalsToPing() {
        
        $blacklist = $this->getEntityManager()->getRepository(Blacklist::class)
                ->createQueryBuilder('bl')
                ->select('bl.uuid');
        
        $whitelist = $this->getEntityManager()->getRepository(Whitelist::class)
                ->createQueryBuilder('wl')
                ->select('wl.uuid');
        
        $qb = $this->createQueryBuilder('j');
        $qb->andWhere('j.status != :status');
        $qb->setParameter('status', 'ping-error');
        $qb->andWhere($qb->expr()->notIn('j.uuid', $blacklist->getDQL()));
        $qb->andWhere($qb->expr()->notIn('j.uuid', $whitelist->getDQL()));
        return $qb->getQuery()->execute();
    }
    
}
