<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TermOfUseRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TermOfUseRepository extends EntityRepository {

    /**
     *
     */
    public function getTerms() {
        return $this->findAll(array(), array(
            'weight' => 'ASC',
        ));
    }

    /**
     *
     */
    public function getLastUpdated() {
        $qb = $this->createQueryBuilder('t');
        $qb->select('MAX(t.updated)');
        return $qb->getQuery()->getSingleScalarResult();
    }

}
