<?php

namespace AppBundle\Repository;

/**
 * TermOfUseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TermOfUseRepository extends \Doctrine\ORM\EntityRepository
{
}
