<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TermOfUseHistoryRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TermOfUseHistoryRepository extends EntityRepository {
}
