<?php

namespace AppBundle\Repository;

/**
 * TermOfUseHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TermOfUseHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
